# -*- coding: utf-8 -*-
"""LabTask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnNIDIVd_J67WEaAyrHXQPi98IuBFWyE

# ***ESHAL*** ***KHAN***
***SP23-BCS-095***

**MATPLOTLIB**

library used for visualition of data through graphs ,etc no storage included

**NUMPY**

library for advance numerical computation

**LIST**
"""

Num = [1,2,3,4,5,6,7,8,9,10]
print(Num)

"""**Sum**"""

Num = [1,2,3,4,5,6,7,8,9,10]
print(sum(Num))

"""**Max**"""

Num = [1,2,3,4,5,6,7,8,9,10]

print(max(Num))

"""**Min**"""

Num = [1,2,3,4,5,6,7,8,9,10]
print(min(Num))

"""**Append**"""

Num = [1,2,3,4,5,6,7,8,9,10]
Num.append(7)
print(Num)

"""**Remove**"""

Num = [1,2,3,4,5,6,7,8,9,10]
Num.remove(4)
print(Num)

"""**Sorting**"""

Num = [1,2,3,4,5,6,7,8,9,10]
print('Ascending:',sorted(Num))
print('Descending:', sorted(Num,reverse = True))

"""**TUPLE**

**creating** **a** **tuple**
"""

fruits = ("apple","orange","watermelon","cherry")
print(fruits)

"""  **Print** **second** **and** **last** **element**"""

fruits = ("apple","orange","watermelon","cherry")
print(fruits[0])
print(fruits[-1])

"""**try** **to** **modify**"""

fruits = ("apple","orange","watermelon","cherry")
print(fruits)
fruits[3] = "pineapple"

"""**convert the** **tuple** **into** **a** **list** **and** **modify**"""

fruits = ("apple","orange","watermelon","cherry")
fruit = list(fruits)
fruit[3] = "pineapple"

print('modified list : ',fruit)

"""**SET**

**create two set with some common and unique elements**
"""

from typing import Union
setA = {1,2,3,4,5,6}
setB = {4,5,6,7}

print('Union of Sets:',setA.union(setB))
print('intersection of Sets:',setA.intersection(setB))
print('Difference of Sets:',setA.difference(setB))

"""**Add a new element to a set**"""

setA = {1,2,3,4,5,6}
setA.add(9)
print(setA)

"""**Remove a element from Set**"""

setA = {1,2,3,4,5,6}
setA.remove(4)
print(setA)

"""**DICTIONARY**

**create a dictionary**
"""

students = {'Eshal': 95 ,'Maryam' : 153 , 'Amna' : 71 }
print(students)

"""**Update** **values**"""

students = {'Eshal': 95 ,'Maryam' : 153 , 'Amna' : 71 }
students['Eshal'] = 90
print(students)

"""**try to update key**"""

students = {'Eshal': 95 ,'Eshal' : 153 , 'Eshal' : 71 }
print(students)